"""
StreamAttention - Novel Fused Online Softmax Attention

A breakthrough attention mechanism that computes softmax normalization "on the fly"
using running accumulators, achieving both memory efficiency and numerical stability
in a single kernel pass.

Key Features:
- Single-pass attention computation without materializing attention matrix
- Online softmax with running statistics for numerical stability
- Tiled processing for efficient memory access
- Multi-GPU support through PyTorch Distributed
- Easy integration with existing deep learning workflows
"""

__version__ = "1.0.0"
__author__ = "StreamAttention Team"
__license__ = "Apache-2.0"

from .core.config import StreamAttentionConfig
from .core.fused_online_attention import (
    FusedOnlineAttention,
    create_fused_online_attention,
)
from .core.attention import StreamAttention
from .core.multihead_attention import StreamMultiheadAttention, create_stream_attention
from .core.flashattention_v3 import FlashAttentionV3
from .certified import (
    BlockSummaries,
    CertifiedAttentionOutput,
    CertifiedAttentionStats,
    StreamAttnMetadataCache,
    build_block_summaries,
    certified_attention,
)
from .router import (
    AttentionRouteRequest,
    BackendDecision,
    ActiveCurvePoint,
    CostEntry,
    CostKey,
    Gate1CostModel,
    StreamAttnPolicy,
    StreamAttnRouter,
    normalize_device_class,
)
from .telemetry import ActiveFractionKey, ActiveFractionTelemetry, Prediction
from .gate1 import (
    Gate1RunInfo,
    Gate1Stats,
    dense_attention_forward,
    make_route_request,
    stream_attn_gate1,
    summarize_gate1_raw_stats,
    summarize_gate1_raw_stats_per_head,
)
from .gate0_fused_hybrid import (
    Gate0FusedHybridPolicy,
    Gate0FusedHybridRunInfo,
    Gate0FusedHybridStats,
    Gate0ProjectionMetadata,
    build_gate0_projection_matrix,
    build_gate0_projection_metadata,
    make_gate0_fused_hybrid_workspace,
    stream_attn_gate0_fused_hybrid,
    summarize_gate0_fused_hybrid_raw_stats,
    summarize_gate0_fused_hybrid_raw_stats_per_head,
)
from .decode import (
    DecodeCostEntry,
    DecodeCostKey,
    DecodeCostModel,
    Gate0SeedOnlyBatchedPolicy,
    Gate0SeedOnlyBatchedRunInfo,
    Gate0SeedOnlyBatchedStats,
    STREAMATTN_EXACT_NATIVE_BACKEND,
    STREAMATTN_MODE_EXACT_NATIVE,
    STREAMATTN_MODE_SEED_ONLY_NATIVE,
    STREAMATTN_MODE_VERIFIED_AUTO,
    STREAMATTN_NATIVE_MODES,
    StreamAttnDecodePlan,
    StreamAttnDecodePolicy,
    StreamAttnDecodeWorkspace,
    StreamAttnDecodeWrapper,
    StreamAttnExactNativeDirectRunner,
    StreamAttnSeedOnlyDirectRunner,
    StreamAttnSeedOnlyDecodeService,
    StreamAttnServingInfo,
    decode_cost_model_from_profile_rows,
    find_packaged_gate0_seed_only_batched_policies,
    list_packaged_gate0_seed_only_batched_policies,
    load_packaged_gate0_seed_only_batched_policy,
    packaged_gate0_seed_only_batched_policy_registry,
    normalize_stream_attn_mode,
    stream_attn_decode_plan,
    stream_attn_decode_run,
    stream_attn_exact_native_decode,
    stream_attn_seed_only_decode,
)
from .engine import (
    StreamAttnEngine,
    StreamAttnEnginePlan,
    stream_attn_decode,
    stream_attn_prefill,
    stream_attn_train,
)
from .functional import StreamAttnAttentionInfo, StreamAttnAttentionPlan
from .planning import (
    ATTENTION_CACHE_CONTIGUOUS,
    ATTENTION_CACHE_PAGED,
    ATTENTION_GUARANTEE_DISTRIBUTION_VERIFIED,
    ATTENTION_GUARANTEE_EXACT,
    ATTENTION_GUARANTEE_FULL_CONTEXT_EXACT,
    ATTENTION_GUARANTEE_SCHEDULE_EXACT,
    ATTENTION_ROUTE_ABI_VERSION,
    ATTENTION_ROUTE_GRANULARITY_BATCH,
    ATTENTION_ROUTE_GRANULARITY_KV_GROUP,
    ATTENTION_ROUTE_GRANULARITY_Q_HEAD,
    ATTENTION_PHASE_DECODE,
    ATTENTION_PHASE_PREFILL,
    ATTENTION_PHASE_TRAIN,
    ATTENTION_SCHEDULE_ALL,
    ATTENTION_SCHEDULE_SELECTED,
    AttentionBackendPlan,
    AttentionProblem,
    AttentionRouteCSR,
    AttentionTilePlan,
    AttentionTileSchedule,
    AttentionTileSource,
    fixed_block_tile_ids,
)
from .exact_compiler import (
    ArchitectureResourceModel,
    CandidateResourceEstimate,
    CompiledKernelRecord,
    ExactWorkloadCell,
    GuaranteeClass,
    KernelFamily,
    ResourceLegality,
    ScheduleCandidate,
    UniversalExactManifest,
    default_architecture_resource_models,
    load_universal_exact_manifest,
    matching_kernel_families,
    registered_exact_kernel_families,
)
from .selected_routes import (
    PACKED_ROUTE64_ABI_VERSION,
    PACKED_ROUTE64_ATOMS,
    PACKED_ROUTE64_PAGE_SIZE,
    PACKED_ROUTE64_TOKENS,
    PACKED_ROUTE_FLAG_ALL_HEADS,
    PACKED_ROUTE_FLAG_STRUCTURALLY_FULL,
    PACKED_ROUTE_FLAG_TOKEN_FULL,
    SELECTED_SCHEDULER_COMPACT_STATIC,
    SELECTED_SCHEDULER_STATIC_UNIFORM,
    PackedPagedRoute64,
    prepare_paged_routes64,
)
from .backends.sm90 import ExactDecodePlan
from .paged import (
    PAGED_EXACT_NATIVE_BACKEND,
    PAGED_EXACT_SM80_CP_ASYNC_BACKEND,
    PAGED_EXACT_SM80_GROUPED_BACKEND,
    PAGED_EXACT_SM100_GROUPED_BACKEND,
    PAGED_EXACT_SM100_TGV_BACKEND,
    PROMOTED_PAGED_EXACT_SM100_TGV_SPLITS,
    PAGED_EXACT_SM90_FRAGMENTED_RAGGED_BACKEND,
    PAGED_EXACT_SM90_NHD_FRAGMENTED_BACKEND,
    PAGED_EXACT_SM90_NHD_FRAGMENTED_RAGGED_BACKEND,
    PAGED_QUERY_REFINED_SM90_BACKEND,
    PAGED_QUERY_SELECTED_SM90_BACKEND,
    PAGED_SELECTED_SM90_DYNAMIC_QHEAD_BACKEND,
    PAGED_SELECTED_SM90_STATIC_BACKEND,
    PagedDynamicSelectedDecodePlan,
    PagedDynamicSelectedDecodeRunner,
    PagedExactDecodePlan,
    PagedQuerySelectedDecodePlan,
    PagedQuerySelectedDecodeRunner,
    PagedSelectedDecodePlan,
    PagedSelectedDecodeRunner,
    PagedKVCache,
    build_paged_support_keys,
    choose_paged_exact_splits,
    paged_exact_reference,
    paged_selected_reference,
    stream_attn_paged_dynamic_selected_decode,
    stream_attn_paged_exact_decode,
    stream_attn_paged_query_selected_decode,
    stream_attn_paged_selected_decode,
)

# ``import stream_attention as stream_attn; stream_attn.decode(...)``
decode = stream_attn_decode
prefill = stream_attn_prefill
train = stream_attn_train
from .seed_autotune import (
    SeedKernelAutotuneResult,
    SeedKernelCandidate,
    SeedKernelShape,
    autotune_seed_kernel_mode,
    seed_kernel_candidates,
    seed_shape_from_policy,
)
from .bucket_policy import (
    BucketRouteDecision,
    qwen25_3b_bucket_route_decision,
    qwen25_3b_policy_names_for_bucket,
)

# Utilities
from .utils.memory import (
    MemoryProfiler,
    create_kv_compressor,
    gradient_checkpoint_sequential,
)

# Main API
__all__ = [
    # Main modules
    "StreamAttention",
    "StreamMultiheadAttention",
    "FusedOnlineAttention",
    "StreamAttentionConfig",
    "FlashAttentionV3",
    "BlockSummaries",
    "CertifiedAttentionOutput",
    "CertifiedAttentionStats",
    "StreamAttnMetadataCache",
    "AttentionRouteRequest",
    "BackendDecision",
    "ActiveCurvePoint",
    "CostEntry",
    "CostKey",
    "Gate1CostModel",
    "StreamAttnPolicy",
    "StreamAttnRouter",
    "normalize_device_class",
    "ActiveFractionKey",
    "ActiveFractionTelemetry",
    "Prediction",
    "Gate1RunInfo",
    "Gate1Stats",
    # Factory functions
    "create_stream_attention",
    "create_fused_online_attention",
    "build_block_summaries",
    "certified_attention",
    "dense_attention_forward",
    "make_route_request",
    "stream_attn_gate1",
    "summarize_gate1_raw_stats",
    "summarize_gate1_raw_stats_per_head",
    "Gate0FusedHybridPolicy",
    "Gate0FusedHybridRunInfo",
    "Gate0FusedHybridStats",
    "Gate0ProjectionMetadata",
    "build_gate0_projection_matrix",
    "build_gate0_projection_metadata",
    "make_gate0_fused_hybrid_workspace",
    "stream_attn_gate0_fused_hybrid",
    "summarize_gate0_fused_hybrid_raw_stats",
    "summarize_gate0_fused_hybrid_raw_stats_per_head",
    "DecodeCostEntry",
    "DecodeCostKey",
    "DecodeCostModel",
    "Gate0SeedOnlyBatchedPolicy",
    "Gate0SeedOnlyBatchedRunInfo",
    "Gate0SeedOnlyBatchedStats",
    "STREAMATTN_EXACT_NATIVE_BACKEND",
    "STREAMATTN_MODE_EXACT_NATIVE",
    "STREAMATTN_MODE_SEED_ONLY_NATIVE",
    "STREAMATTN_MODE_VERIFIED_AUTO",
    "STREAMATTN_NATIVE_MODES",
    "StreamAttnDecodePlan",
    "StreamAttnDecodePolicy",
    "StreamAttnDecodeWorkspace",
    "StreamAttnDecodeWrapper",
    "StreamAttnExactNativeDirectRunner",
    "StreamAttnSeedOnlyDirectRunner",
    "StreamAttnSeedOnlyDecodeService",
    "StreamAttnServingInfo",
    "decode_cost_model_from_profile_rows",
    "find_packaged_gate0_seed_only_batched_policies",
    "list_packaged_gate0_seed_only_batched_policies",
    "load_packaged_gate0_seed_only_batched_policy",
    "packaged_gate0_seed_only_batched_policy_registry",
    "normalize_stream_attn_mode",
    "stream_attn_decode_plan",
    "stream_attn_decode_run",
    "stream_attn_exact_native_decode",
    "stream_attn_seed_only_decode",
    "StreamAttnEngine",
    "StreamAttnEnginePlan",
    "StreamAttnAttentionInfo",
    "StreamAttnAttentionPlan",
    "AttentionProblem",
    "AttentionRouteCSR",
    "AttentionTileSource",
    "AttentionTileSchedule",
    "AttentionTilePlan",
    "AttentionBackendPlan",
    "ATTENTION_GUARANTEE_EXACT",
    "ATTENTION_GUARANTEE_FULL_CONTEXT_EXACT",
    "ATTENTION_GUARANTEE_SCHEDULE_EXACT",
    "ATTENTION_GUARANTEE_DISTRIBUTION_VERIFIED",
    "ATTENTION_PHASE_DECODE",
    "ATTENTION_PHASE_PREFILL",
    "ATTENTION_PHASE_TRAIN",
    "ATTENTION_CACHE_CONTIGUOUS",
    "ATTENTION_CACHE_PAGED",
    "ATTENTION_ROUTE_ABI_VERSION",
    "ATTENTION_ROUTE_GRANULARITY_BATCH",
    "ATTENTION_ROUTE_GRANULARITY_KV_GROUP",
    "ATTENTION_ROUTE_GRANULARITY_Q_HEAD",
    "ATTENTION_SCHEDULE_ALL",
    "ATTENTION_SCHEDULE_SELECTED",
    "fixed_block_tile_ids",
    "ArchitectureResourceModel",
    "CandidateResourceEstimate",
    "CompiledKernelRecord",
    "ExactWorkloadCell",
    "GuaranteeClass",
    "KernelFamily",
    "ResourceLegality",
    "ScheduleCandidate",
    "UniversalExactManifest",
    "default_architecture_resource_models",
    "load_universal_exact_manifest",
    "matching_kernel_families",
    "registered_exact_kernel_families",
    "PACKED_ROUTE64_ABI_VERSION",
    "PACKED_ROUTE64_ATOMS",
    "PACKED_ROUTE64_PAGE_SIZE",
    "PACKED_ROUTE64_TOKENS",
    "PACKED_ROUTE_FLAG_ALL_HEADS",
    "PACKED_ROUTE_FLAG_STRUCTURALLY_FULL",
    "PACKED_ROUTE_FLAG_TOKEN_FULL",
    "SELECTED_SCHEDULER_COMPACT_STATIC",
    "SELECTED_SCHEDULER_STATIC_UNIFORM",
    "PackedPagedRoute64",
    "prepare_paged_routes64",
    "ExactDecodePlan",
    "PAGED_EXACT_NATIVE_BACKEND",
    "PAGED_EXACT_SM80_CP_ASYNC_BACKEND",
    "PAGED_EXACT_SM80_GROUPED_BACKEND",
    "PAGED_EXACT_SM100_GROUPED_BACKEND",
    "PAGED_EXACT_SM100_TGV_BACKEND",
    "PROMOTED_PAGED_EXACT_SM100_TGV_SPLITS",
    "PAGED_EXACT_SM90_FRAGMENTED_RAGGED_BACKEND",
    "PAGED_EXACT_SM90_NHD_FRAGMENTED_BACKEND",
    "PAGED_EXACT_SM90_NHD_FRAGMENTED_RAGGED_BACKEND",
    "PAGED_QUERY_REFINED_SM90_BACKEND",
    "PAGED_QUERY_SELECTED_SM90_BACKEND",
    "PAGED_SELECTED_SM90_DYNAMIC_QHEAD_BACKEND",
    "PAGED_SELECTED_SM90_STATIC_BACKEND",
    "PagedDynamicSelectedDecodePlan",
    "PagedDynamicSelectedDecodeRunner",
    "PagedExactDecodePlan",
    "PagedQuerySelectedDecodePlan",
    "PagedQuerySelectedDecodeRunner",
    "PagedSelectedDecodePlan",
    "PagedSelectedDecodeRunner",
    "PagedKVCache",
    "build_paged_support_keys",
    "choose_paged_exact_splits",
    "paged_exact_reference",
    "paged_selected_reference",
    "stream_attn_paged_dynamic_selected_decode",
    "stream_attn_paged_exact_decode",
    "stream_attn_paged_query_selected_decode",
    "stream_attn_paged_selected_decode",
    "stream_attn_decode",
    "decode",
    "stream_attn_prefill",
    "prefill",
    "stream_attn_train",
    "train",
    "SeedKernelAutotuneResult",
    "SeedKernelCandidate",
    "SeedKernelShape",
    "autotune_seed_kernel_mode",
    "seed_kernel_candidates",
    "seed_shape_from_policy",
    "BucketRouteDecision",
    "qwen25_3b_bucket_route_decision",
    "qwen25_3b_policy_names_for_bucket",
    # Utilities
    "MemoryProfiler",
    "create_kv_compressor",
    "gradient_checkpoint_sequential",
    # Version
    "__version__",
]
