name: Build Wheels

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sm: [80, 90]
    env:
      TORCH_CUDA_ARCH_LIST: ${{ matrix.sm }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build wheel
        run: |
          python -m build --wheel
